### ISSUE TITLE
Locked Field

### ISSUE THREAD

**Issue by trisosamu** [glpi-project/glpi-agent#129]
Hi,
There isn't the locked field tab on plugin for lock the rewriting of data come from computer inventory (like lock alternative name, domain name, pc name or others)

**Comment by g-bougard** [comment]
Hi @trisosamu 

you're talking about a server issue, not an agent one. So this is the wrong place to report.

Anyway, your issue is still probably fixed by glpi-project/glpi#11538 which will be integrated in coming soon (probably next week) 10.0.1 GLPI version.

So please, try the PR or wait for that new version and report an issue on glpi project if you still have an issue.
