### ISSUE TITLE
problem on inventory 

### ISSUE THREAD

**Issue by hey0010** [glpi-project/glpi-agent#157]
### Documentation

Yes, I read it

### Solution search

Yes, I read it

### Professional support

Yes, I know

### Is your help request related to a problem?

inventory of windows and linux assets must be done with seprate agents?
I mean an agent only for ssh and another for WinRM?
when I try to inventory both linux and windows assets by a single agent I face this error:
```
> sudo glpi-remote add ssh://glpi:'**'@*****  --target server0
> sudo glpi-remote list
index  deviceid                           url                                  target   Next run date
    1  *****8  ssh://glpi:*@*****        server0  on next agent run
> sudo glpi-remote add winrm://glpi:'**'@**** --target server0
Can't call method "debug2" on an undefined value at /usr/share/glpi-agent/lib/GLPI/Agent/Task/RemoteInventory/Remote/Ssh.pm line 34.
```
### Expected behavior

any suggestion would be appreciated.

### Actions you've considered

any suggestion would be appreciated.

**Comment by g-bougard** [comment]
Hi @hey0010 

as a short answer, no it is not requested to have one agent by asset to inventory or one agent by remote access protocol.

About your error, it is related to ssh protocol where you're telling you are adding a winrm remote and still have successfully added one ssh remote. For me this is just impossible, but I may have missed a very strange bug. You'll have to detail all the step you've done since the agent installation to reach this error so I can reproduce. Also you should tell on which OS you have installed the agent and with which method (perl installer, snap package, AppImage, from source ?).

**Comment by hey0010** [comment]
Hi
I tried almost all the possible installation ways for GLPI agent and face the following problem in all the ways. The following error is in --debug mode.
```
sudo glpi-remote add winrm://*******:'*******'@********* --target server0 --debug
Current vardir: /var/lib/glpi-agent
[debug] Logger backend Stderr initialized
[debug] [http client] authentication required, submitting credentials
[debug] [http client] authentication required, trying basic with glpi user (WSMAN)
Can't call method "debug2" on an undefined value at /usr/share/glpi-agent/lib/GLPI/Agent/Task/RemoteInventory/Remote/Ssh.pm line 34.
```
thank you in advance

**Comment by g-bougard** [comment]
Can you try using PASSWORD environment variable to set password in the case you password uses special chars which has some other meaning on command line ?

**Comment by hadim85** [comment]
> Can you try using PASSWORD environment variable to set password in the case you password uses special chars which has some other meaning on command line ?

would you please tell me your OS version that you develop and test your software features? so we migrate to your recommended OS?

**Comment by g-bougard** [comment]
Hi @hadim85 

I'm developing & testing on many linux versions (mostly Fedora, Debian/Ubuntu, CentOS). If the issue is related to your specific linux version, you should report your own OS version so I can try to reproduce the case.

For ssh remote inventory I just recommend to avoid CentOS as it may not provide libssh2 library which is required for user/password authentication. You still can use CentOS if you manage to setup more secure pubkey authentication.

**Comment by hadim85** [comment]
The problem occurred when you want to add a windows remote inventory after adding a linux machine with ssh!

as you can see, when I add a windows remote machine immediately after adding linux ones, faced this Error.

I'm trying to add windows remote machine but I unfortunately face ssh Error!!!

```
sudo glpi-remote add ssh://glpi:'**'@*****  --target server0
sudo glpi-remote list
index  deviceid                           url                                  target   Next run date
    1  *****8  ssh://glpi:*@*****        server0  on next agent run
sudo glpi-remote add winrm://glpi:'**'@**** --target server0
Can't call method "debug2" on an undefined value at /usr/share/glpi-agent/lib/GLPI/Agent/Task/RemoteInventory/Remote/Ssh.pm line 34.
```

**Comment by g-bougard** [comment]
This is also what I understand, but you didn't answer my question:
> If the issue is related to your specific linux version, you should report your own OS version so I can try to reproduce the case.

**Comment by hadim85** [comment]
> This is also what I understand, but you didn't answer my question:
> 
> > If the issue is related to your specific linux version, you should report your own OS version so I can try to reproduce the case.

I use Ubuntu 20.04 with perl 5.30.  I have tested both installing latest glpi-agent  from source and installing from perl command, the error is produced in both cases.
```
# glpi-agent --version
GLPI Agent (1.4-1)
Built by Debian
Source time: 2022-07-01 09:21
```

**Comment by g-bougard** [comment]
Hi @hey0010 & @hadim85,
I finally managed to reproduce and find the problem. This was happening when a ssh remote is defined before a winrm one and libssh2 is used.
Next nightly build should work properly.
