### ISSUE TITLE
Multiple entries for "Windows Apps", Edge and so on..

### ISSUE THREAD

**Issue by vollkommenIrrelevant** [glpi-project/glpi-agent#183]
### Bug reporting acknowledgment

Yes, I read it

### Describe the bug

I got on single computer multiple entries for Windows Apps,Edge and so on in GLPI with GLPI-Agent. The Versionsnumbers and Dates (masked for privacy) are all different, so how to deal with it?

![grafik](https://user-images.githubusercontent.com/25504254/179797023-5732ab6d-2e3f-4432-8c48-44f1ad2c3ff8.png)

![grafik](https://user-images.githubusercontent.com/25504254/179797282-e3bcded2-ad49-4939-9126-912e1197a525.png)

### To reproduce

Open one Computer
Select Software
See

### Expected behavior

Only show the actual installed Version

### Operating system

Windows

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

10.0.1

### Additional context

GLPI inventory, past fusioninventory

**Comment by vollkommenIrrelevant** [comment]
bump

**Comment by g-bougard** [comment]
Hi @vollkommenIrrelevant 

this is not a bug. This can happen if you have different users on the system for which a Windows Store app has been installed at different times (because for example different users were connected on the computer at some time in the past). The system will probably update the app next time the user will connect.

You can investigate what package is installed in which version for which user using the [Get-AppxPackage](https://docs.microsoft.com/en-us/powershell/module/appx/get-appxpackage) PS command. After that, you may decide to make some maintenance to remove users or upgrade the package for them, at your choice.

Anyway, this is not a GLPI-Agent issue.
