### ISSUE TITLE
Problem scan with error 400

### ISSUE THREAD

**Issue by leslie-UFT** [glpi-project/glpi-agent#213]
### Documentation

Yes, I read it

### Solution search

Yes, I read it

### Is your help request related to a problem?

I would like to know if it really works to configure with a plugin for inventory only by winrm, snmp or ssh (linux) without having to install the agent on other machines.
In addition, having to add the GLPI Inventory plugin to leave the native features as much as possible and without installing the agent on client machines, as well as inventorying in an IP range only

### Expected behavior

When click Results and after click em scan again, only show error 400 Bad Request
with url `http://10.10.24.1:62354/toolbox//toolbox/inventory` and even if you put the url : `http://10.10.24.1:62354/toolbox/inventory`
has the same problem:
https://drive.google.com/file/d/1QnoLLzMVXv7TkyoD64MfPn9L4YbFcL-2/view?usp=sharing

### Actions you've considered

With config:
https://drive.google.com/file/d/10nqvBM1fpX3u1cI9wFLlQAlAAVoxebut/view?usp=sharing

**Comment by g-bougard** [comment]
Hi @leslie-UFT 

first of all, winrm & ssh are handled by **remoteinventory** task and snmp by **netdiscovery** & **netinventory** tasks. You can use **GLPI Inventory plugin** to manage **netdiscovery** & **netinventory** tasks so you can only setup your SNMP scans in GLPI for now.

GLPI Agent Toolbox UI will only permit to locally store your XMLs generated by **netdiscovery** & **netinventory** tasks. So you'll still have to import them in GLPI (manually or automatically with glpi-injector script).
Since last week, GLPI Agent Toolbox includes a dedicated page to manage "remotes" for remoteinventory task. You'll have to use a nightly built glpi-agent or wait for coming soon glpi-agent 1.5. Or you can manage "remotes" with the glpi-remote script as explained in online documentation.

About your SNMP scan with ToolBox, you still have to run the netscan from the "Inventory" page before seeing something in "Results" page. You also must have network devices or printers in the IP range which support SNMP with the credentials you setup and associated with your IP range. But you should better create dédicated netdiscovery and netinventory tasks with GLPI Inventory plugin.

You still have to install at least one agent somewhere. But yes, it can permit you to remoteinventory every thing supported on your network.

**Comment by g-bougard** [comment]
Oh I finally understood you don't have the "Inventory" page in ToolBox UI. You need to enable it in the config. You can do it from the configuration page clicking on the "gear" on the top right.

**Comment by g-bougard** [comment]
Closing without user answer, feel free to re-open if you have more to share.
