### ISSUE TITLE
Agent Status Unknown

### ISSUE THREAD

**Issue by youssef-chtourou** [glpi-project/glpi-agent#225]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

The agent work fine. and i get the wanted data

but in " inventory information " section , the status of agent is " unknown "

can someone have a idea please ??

![image](https://user-images.githubusercontent.com/71817433/193466916-e27a0f9b-c072-41d7-9f8d-a526d6f258a0.png)

### To reproduce

N/A

### Expected behavior

N/A

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.3

**Comment by g-bougard** [comment]
Hi @g-bougard 
first of all, this is not a bug, and even this is a GLPI UI related question.
Then the status is "unknown" by default as GLPI have to request the URL `http://<agent-ip>:62354/status`. The request is only tried if you manually click on the "refresh" icon next to the "Agent status" title.
And even, the status can be kept unknown if the agent is not responding to the refresh request when:
* the agent doesn't listen to requests because of `no-httpd`, `httpd-ip` or `httpd-port` configuration,
* the agent doesn't listen because the service is down or not configured to run as a service,
* the agent doesn't trust the request as GLPI is not configured as `server` target or it can't resolv the GLPI server ip,
* the request is blocked due to a firewall configuration, or the agent is behind a firewall,
* the agent is in a isolated network without network route to the GLPI server.

And finally, this can only be a bug on GLPI or agent side if none of the above cases is related to your case.

You should just consider this information obtained with the refresh button as a helper. The agent is mostly passive and the best way to check the agent status remains to check the computer where it should be running by checking the status of the process and eventually the content of its log file.

**Comment by kintaro1981** [comment]
Another thing to double check is the proxy configuration in GLPI.
In my case solved the problem.
