### ISSUE TITLE
SSL Options don't understand

### ISSUE THREAD

**Issue by Jason-Linux** [glpi-project/glpi-agent#241]
### Documentation

Yes, I read it

### Solution search

Yes, I read it

### Professional support

Yes, I know

### Is your help request related to a problem?

No

### Expected behavior

HI, I would like to know what i need to fill in "Remote Targets SSL Options"
I don't understant what i need to fill in "certificate directory" "CA Certificate File" and fingerprint.

Can You help me please

### Actions you've considered

I tried create pem and pub certificate and key assic directory in first shield and cert file in cert file, and fingerprint of my website but don't work.

Glpi agent work with no check SSL

### Additional context

I use Reverse proxy between me and glpi-server

**Comment by SteadEXE** [comment]
Hello, I don't know if you checked it already maybe it can help you:
https://glpi-agent.readthedocs.io/en/latest/configuration.html

**Comment by SteadEXE** [comment]
Apparently if you want to use SSL fingerprint, you need to start the agent with no-ssl-check, then in the logs it will show you something like: "SSL server certificate fingerprint:" and you need to put the fingerprint in ssl-fingerprint (for me it was sha256$fe2...........).
Then you can disable no-ssl-check.

ca-cert-dir seems to no longer be working since 1.3.
@g-bougard I don't know it is intentional or a bug for ca-cert-dir, but ca-cert-dir alone no longer works.

**Comment by g-bougard** [comment]
Hi @SteadEXE

`ca-cert-dir` was broken in 1.3 due to my mistake. But 1.4 was quickly released to fix that, if not, this a bug and you should open an issue for that O:)
If you're on windows or MacOSX, you can register the server certificate in system keystore/keychain and it should be used automatically, see #33 & #108.

**Comment by SteadEXE** [comment]
Maybe I am wrong, anyway, I opened a separate issue, I don't want to hijack @Jason-Linux's issue :)

**Comment by Jason-Linux** [comment]
No problem @SteadEXE, fingerprint work but now i have problem with network deployment.
I use cmdline script  : 
I exec the msi with :
	`\\Server\Application\GLPI-Agent-1.4-x64.msi /i /quiet RUNNOW=1 SERVER='https://glpi.sandbox.local/front/inventory.php' SSL-FINGERPRINT=0000000000000000000000000000000000000000000000000000000 DEBUG=2 EXECMODE=2 ADD_FIREWALL_EXCEPTION=1 INSTALLDIR='C:\Program Files\GLPI-Agent' BACKEND_COLLECT_TIMEOUT=180 LOGFILE='C:\Program Files\GLPI-Agent\logs\glpi-agent.log' LOGGER=file TASK_DAILY_MODIFIER=1 TAG=Enterprise`
	
Can you help me for that ?

**Comment by SteadEXE** [comment]
What isn't working exactly?

**Comment by g-bougard** [comment]
@Jason-Linux 
Probably `SSL-FINGERPRINT` should be replaced by `SSL_FINGERPRINT`.
Be sure also to not run this command in a PowerShell console.
Also INSTALLDIR, BACKEND_COLLECT_TIMEOUT, LOGFILE & LOGGER are useless if you're just using the current default.

**Comment by Jason-Linux** [comment]
i don't run it in POWERSHELL, i run in Windows command line, never install.
I see this : 
![image](https://user-images.githubusercontent.com/72259326/196170474-1b491fde-d8c3-470b-abe9-fd4235d7c8ff.png)
and
![image](https://user-images.githubusercontent.com/72259326/196170551-d713e9f8-b155-49c7-b03c-5bd07a93c65a.png)

**Comment by Jason-Linux** [comment]
I delete /quiet to obtain previous results

**Comment by g-bougard** [comment]
You should probably try the [VBS Installer](https://glpi-agent.readthedocs.io/en/latest/installation/index.html#large-installations).
When it doesn't install, this is generally because you have a typo in your commandline or in your options like using a dash `-` in place of an underscore `_` in `SSL-FINGERPRINT`.

**Comment by Jason-Linux** [comment]
I Can't use VBS Installer beacause i need TAG to separate different Part of Enterprise.

**Comment by SteadEXE** [comment]
@Jason-Linux , you can configure different tag using different VBS (edit a VBS per part).
Or you can do like we do, we install the agent with only the server URL. 
And then we use the ADMX to deploy the config through GPO. 
So you can specify differents settings if you want per group for example on your active directory.

But I am suprised that MSI doesn't work with TAG, did you check this documentation? I never tried on my own, tbh.
https://glpi-agent.readthedocs.io/en/latest/installation/windows-command-line.html#command-line-parameters

ADMX can be found there: https://github.com/glpi-project/glpi-agent/tree/develop/contrib/windows

**Comment by Jason-Linux** [comment]
TAG can be use with .MSI. but it seems that the vbs don't have TAG entry

**Comment by g-bougard** [comment]
Just add it to the `SetupOptions` variable string value.

Anyway, I'm closing this issue as it is now out of initial topic and I assume you figured out it by now.
