### ISSUE TITLE
toolbox functionality [add ip range] enhancement

### ISSUE THREAD

**Issue by c3ph3us** [glpi-project/glpi-agent#253]
### Documentation

Yes, I read it

### Professional support

Yes, I know

### Is your feature request related to a problem?

toolbox usage

### Expected behavior

**request:**
in Inventory tab/window under Network scan Choose IP range selection **ADD LINK ->  NEW IP RANGE** same as for (new tag) tag selection box  

**justification:**
when toolbox is used by default has no links to ip range thus the user need to dig up through options/settings and enable those to add the range 

### Alternatives you've considered

digging up agent manuals for ip range edition, filling a bug :D

### Additional context

[GLPI Agent v1.5-dev]
ToolBox Plugin v1.1

**Comment by g-bougard** [comment]
Hi @c3ph3us 

after the ToolBox UI rework, and as the task management has evolved, it seems to me your issue is now obsolete.

Can you confirm ? Or do you think the UI should still be improved for that point ?

Best regards.

P.S.: You can discover the new UI with current nightly build. And it is documented here: https://glpi-agent.readthedocs.io/en/latest/plugins/toolbox-plugin.html

**Comment by g-bougard** [comment]
Closing without feedback,

Feel free to comment.
