### ISSUE TITLE
glpi-remote : command 'can' still not supported

### ISSUE THREAD

**Issue by tech62** [glpi-project/glpi-agent#268]
### Documentation

Yes, I read it

### Solution search

Yes, I read it

### Is your help request related to a problem?

Yes

### Expected behavior

Start a scan of the host or ip range

### Actions you've considered

I got `TODO: command 'scan' still not supported` when i run `glpi-remote scan 10.10.2.30 | glpi-injector -url https://support.glpi.lan:62354/proxy/glpi`

Is it an expected behavior ?

### Additional context

Version Glpi-agent 1.4

**Comment by g-bougard** [comment]
Hi @tech62 
as this is reported, "scan" `glpi-remote` command is still in development.
Read the online documentation to know what you can do for now with this command:
https://glpi-agent.readthedocs.io/en/latest/tasks/remote-inventory.html
&
https://glpi-agent.readthedocs.io/en/latest/man/glpi-remote.html
I can also advise you to use the nightly GLPI-Agent as many fixes and improvement has been included for remoteinventory task since GLPI-Agent 1.4.

**Comment by tech62** [comment]
Thanks for your reply
