### ISSUE TITLE
deployed files are not removed after task has finished

### ISSUE THREAD

**Issue by TheRich-71** [glpi-project/glpi-agent#283]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

Each deploy task creates files in \var\fileparts and a folder containing the deployed filestructure in \var\workdir. After the task has finished (no matter if succeeded or failed), the files are still kept there unnecessarily using diskspace.

### To reproduce

1. Create a deploy task with files
2. Run the task
3. Verify the content of \var\workdir

### Expected behavior

I would expect the files to be removed after the task was finished

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

Other (See additional context below)

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Other (See additional context below)

### Additional context

GLPI 10.0.5, GLPIInventory 1.0.6 (Please update the DropDowns with recent versions)

**Comment by g-bougard** [comment]
Hi @TheRich-71 
by default, these files can be kept in case of failure to limit the amount of retrieved datas during the next try.
Also if P2P support is enabled, the file are kept for some time.
Anyway, the service is always running a maintenance task which will cleanup the folder if the disk becomes out of space.

Anyway, since GLPI-Agent 1.4, I worked a little on Deploy task so maybe the current nightly buid may make a better job for cleaning deployed files.
Can you give it a try and tell me if it's better ?
Get it there: https://nightly.glpi-project.org/glpi-agent/

Also, you may want to enable debug mode to 2 to see in log and eventually sharing the output here if you think it's not correct. The debug log will show you the maintenance task activity.

**Comment by g-bougard** [comment]
Closing without user feedback.
Feel free to update or even re-open.
