### ISSUE TITLE
Fatal error in netinventory task

### ISSUE THREAD

**Issue by Giudy** [glpi-project/glpi-agent#353]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

I'm a GLPI partner

### Describe the bug

With the nightly build
[Tue Feb 28 16:47:16 2023][debug] GLPI Agent (1.5-gitec37be05)
of yeaterday night, the discovery is not working any more.
the agent is used on Linux and it is used mainly to do discovery and inventory
discvery works well but as soon as it start the inventory part we find this log entry before the agent close

[Tue Feb 28 18:47:08 2023][debug] All netdiscovery threads terminated
[Tue Feb 28 18:47:08 2023][error] Can't use string ("") as a HASH ref while "strict refs" in use at /usr/share/glpi-agent/lib/GLPI/Agent/Task/NetInventory.pm line 55.

it seems that there is an issue with a device without IP?
 after this issue the inventory task stays in running until the next round with the agent (when it fail)
thanks

davide

### To reproduce

.

### Expected behavior

haoing the inventory

### Operating system

Linux

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

10.0.6

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.1.0

**Comment by stonebuzz** [comment]
Hi @Giudy 
can you enable debug mode from ```GLPI-agent``` and past here the log file ?
I need to check ```XMl``` response from GLPI when ```GLPI-Agent``` ask informations about ```netinventory``` job.
Best regards

**Comment by stonebuzz** [comment]
Have you the same problem with latest official release?

https://github.com/glpi-project/glpi-agent/releases/tag/1.4

Can you try with it?

Best regards

**Comment by trasher** [comment]
You say "the discovery is not working any more.". Could you tell us with which exact version it was working?

**Comment by g-bougard** [comment]
Hi @Giudy 

thank you for your report.

I think the agent receives a netinventory job with an empty device. This code didn't really change since FIA fork. Only the XML support has changed and this may be part of the problem. The fact is really the agent should receive a job with a device to scan, but without knowing any information on the device like the ip to contact. So this may be a side-effect of a problem on GlpiInventory side. ~~I guess even the problem may be present also in FusionInventory plugin.~~ In that case, the plugin should not tell there's a device to scan.

I even guess this may work at some time. Maybe after a specific device is shutdown.

I remember to have see this problem with a customer who run netdiscovery task once a week and netinventory task each day. Can you try to run netdiscovery and then netinventory ? If this works, you may have to always run netdiscovery before netinventory. Maybe some critical information is outdated and remove automatically via an automatic action.

Anyway, I'll fix the error support on agent side. But you may don't understand why a device is not more inventoried as the agent won't be able to access it without an ip.

_P.S.: After some test, my guess becomes it's probably a GlpiInventory plugin regression. But the agent still need to tolerate wrong XML and just ignore the wrong formated job._

**Comment by g-bougard** [comment]
@Giudy 

Next nightly build should fix your issue on agent-side.

You will probably start to see in agent log messages like:
```
[error] invalid device found
```
or even:
```
[error] invalid job: no valid device defined
```
This means a least one device won't be inventoried by netinventory task even if it has been discovered before.

In that case, you should enable `debug = 2` in agent configuration and reports the log where we can see the XML message sent by the server which defines the netinventory job. With that, this may help to see an issue with your tasks definitions or this is a problem with the plugin and you should open an issue on the GlpiInventory plugin project.

If you're in a hurry, you can take the development build from this GH Actions run after it has been completed:
https://github.com/glpi-project/glpi-agent/actions/runs/4302708181

**Comment by Giudy** [comment]
Hi guys, sorry for being late. yes, the debug was on and I did past the related lines to the error
tonight I will give a look to the new version!
thank you

davide

**Comment by stonebuzz** [comment]
We need all stacktrace (not only part related to error)

**Comment by Giudy** [comment]
Just to add infos: with 1.4 we didn't have any issue

**Comment by Giudy** [comment]
Hi , here the full log using the nightly build of last monday night


davide

**Comment by g-bougard** [comment]
Hi @Giudy 
this log is not useful as you set `debug = 1` in conf. As I said, only the one when `debug = 2` is set is really meaningful when debugging such problem.

**Comment by Giudy** [comment]
Yep, my mistake. I did set up the debug level in the agent.cfg but it seems that if I launch the agent manually t does not get the debug level if I use the --debug option.
So, here it is with the --debug --debug option
davide
[log.txt](https://github.com/glpi-project/glpi-agent/files/10893113/log.txt)

**Comment by stonebuzz** [comment]
Hi @Giudy 
i found two entries with empty ```DEVICE``` node (for ```netinventory```)

```xml
	<OPTION>
		<NAME>SNMPQUERY</NAME>
		<PARAM/>
		<DEVICE/>
	</OPTION>
	<OPTION>
		<NAME>SNMPQUERY</NAME>
		<PARAM/>
		<DEVICE/>
	</OPTION>
```

can you check from your GLPI if you have tasks without target ?

Best regards

**Comment by g-bougard** [comment]
Hi @Giudy 
before you fix any task, did/can you also test with latest nightly built agent to see if at least it doesn't block ?

**Comment by Giudy** [comment]
Yep it did the job! perfect! Thank you!
No, There was not any job with empty target anyway.

Just a note, really not important, now, in the tasks-Monitoring/Logs the printer task is not any more correctly linked to the working one as it does not show any more the status of the job.
It stays like this:
![image](https://user-images.githubusercontent.com/7987648/223070292-fb594207-974a-45e8-bd51-65df1aacdaeb.png)
while , if I go directly in the task, I see
![image](https://user-images.githubusercontent.com/7987648/223070420-4977e0a7-9822-44d9-aaf6-1c261f3752b5.png)

**Comment by stonebuzz** [comment]
Can you create another issue for this problem ?

Concerning the empty ```DEVICE``` node, I can not reproduce, and without reproduction step it will be complicated to correct this problem

Best regards

**Comment by stonebuzz** [comment]
I guess the fix in the agent is enough

**Comment by Giudy** [comment]
yep, confirmed! thank you
