### ISSUE TITLE
GLPI Agent isn't able to report

### ISSUE THREAD

**Issue by jcsanchezrb** [glpi-project/glpi-agent#478]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

The GLPI agent logs says: 

[Sun Sep 10 20:19:50 2023][error] [http client] communication error: 500 Internal Server Error, JSON does not validate. Violations:
"ISCSI" does not match to ^(SCSI|HDC|IDE|USB|1394|SATA|SAS|ATAPI)$ at #->properties:content->properties:storages->items[0]:0->properties:interface
[Sun Sep 10 20:19:50 2023][error] [http client] server error: JSON does not validate. Violations:
"ISCSI" does not match to ^(SCSI|HDC|IDE|USB|1394|SATA|SAS|ATAPI)$ at #->properties:content->properties:storages->items[0]:0->properties:interface

### To reproduce

Force inventory and then view agent logs.

### Expected behavior

ISCSI is a valid kind of storage in Windows.

### Operating system

Windows

### GLPI Agent version

1.5

### GLPI version

10.0.x (See additional context below)

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.2.3

**Comment by g-bougard** [comment]
Hi @jcsanchezrb 

when you are facing a 500 Internal Server Error from the agent, you only have the agent reporting an error triggered on the server side.

This error has still been reported and was fixed in GLPI latest versions.

I don't know which GLPI version you have as you didn't report it in the "Additional context" as you should have choosing "10.0.x". But please, upgrade your GLPI.
