### ISSUE TITLE
Missed RPM dependence package

### ISSUE THREAD

**Issue by nchizhov** [glpi-project/glpi-agent#508]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

After install all dependencies from rpm-package and GLPI-agent on CentOS 8 and running agent daemon - I have an error in agent logs:
`Can't load XML::LibXML required library`

### To reproduce

1. Install all required dependencies in glpi-agent rpm-package
2. Install glpi-agent tpm-package
3. Configure config-file
4. Start glpi-agent daemon
5. Wait for sending prolog request to server

### Expected behavior

Add perl XML::LibXML library to dependencies of glpi-agent rpm-package

### Operating system

Linux

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

Other (See additional context below)

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Other (See additional context below)

### Additional context

GLPI-Agent Night build - gita3965103

**Comment by g-bougard** [comment]
Hi @nchizhov 

thank you for your report.

Indeed I found this dependency is missing probably since the d7f2df8 commit which has been introduced to fix #438. That change made rpmbuild to no more identify this library as a requirement. Since then, we indeed need to force that requirement in the rpm package spec file.

I'm pushing the required change.

**Comment by g-bougard** [comment]
Next nightly build will fix your issue.

Thank you again for the report.
