### ISSUE TITLE
GLPI Netinventory 1.6  Parallel::ForkManager

### ISSUE THREAD

**Issue by JackTor** [glpi-project/glpi-agent#521]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

Hi, 

I am testing night build agent glpi but when i execute it's wrong:

Can't locate object method "start_child" via package "Parallel::ForkManager" at /usr/share/glpi-agent/lib/GLPI/Agent/Task/NetInventory.pm line 160.

The package perl-Parallel-ForkManager-1.18-2.el7.noarch already installed and latest version and it's was work with glpi-agent stable 1.5

### To reproduce

Install GLPI Agent 1.6 rpm and SNAP

wget https://nightly.glpi-project.org/glpi-agent/glpi-agent-1.6-git16d14304-with-snap-linux-installer.pl or https://nightly.glpi-project.org/glpi-agent/glpi-agent-1.6-git16d14304-linux-installer.pl (fails with the two installers)
chmod +x glpi-agent-1.6-git16d14304-with-snap-linux-installer.pl
./glpi-agent-1.6-git16d14304-with-snap-linux-installer.pl --type=all
 glpi-netinventory --host 192.168.0.1 --credentials version:2c,community:public

Can't locate object method "start_child" via package "Parallel::ForkManager" at /usr/share/glpi-agent/lib/GLPI/Agent/Task/NetInventory.pm line 160.

### Expected behavior

The command should execute correctly

### Operating system

Linux Oracle Linux 7.9 UEK

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

Other (See additional context below)

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Other (See additional context below)

### Additional context

GLPI Version: 10.0.10
GLPI Inventory: 1.3.0

**Comment by g-bougard** [comment]
Hello @JackTor 

thank you for your report.

Since a week nightly builds now includes a full refactoring of NetDiscovery & NetInventory tasks. They now uses Parallel::ForkManager in place of multi-threading. Using this library is more stable and reliable.

By the way, I see the Parallel::ForkManager version on older linux distro is not up-to-date. You have v1.18 on your distro and according to the [Parallel::ForkManager official source](https://metacpan.org/pod/Parallel::ForkManager), the latest version in v2.02 and I uses this version on my development platform which is a Fedora 38. It seems so we are missing the `start_child` method in older versions. That's a shame they didn't use a stable API since 1.0. I'll check what I can do in GLPI Agent to overcome this problem before next release.

**Comment by JackTor** [comment]
Thanks!

**Comment by g-bougard** [comment]
Hi @JackTor 

sorry for the delay, but here is there. I removed the usage of newer api to keep the task compatible on older platforms.

Next nightly build should make the task works for you.
