### ISSUE TITLE
uninstalling glpi-agent leave directories and files in the installation directory

### ISSUE THREAD

**Issue by kintaro1981** [glpi-project/glpi-agent#522]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

Uninstalling glpi-agent leave behind:

- installation directory
-- logs directory
-- var directory
-- local inventory xml file

### To reproduce

Install glpi-agent with this setup options:
/quiet RUNNOW=1 SERVER=http://glpi/plugins/glpiinventory LOCAL=""C:\Program Files\GLPI-Agent"" DEBUG=1 AGENTMONITOR=1 ADD_FIREWALL_EXCEPTION=1"

Run an inventory
Uninstall glpi-agent

### Expected behavior

No trace of c:\program files\glpi-agent\ directory

### Operating system

Windows

### GLPI Agent version

1.5

### GLPI version

10.0.9

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.2.3

**Comment by g-bougard** [comment]
Hi @kintaro1981 

just found a problem in the packaging and it seems it prevented the removing of logs, etc & var folders. I still need to validate the fix is correct, but you'll be able to test with the next nightly build.

Then feel free to reopen if this doesn't fix the problem.

In your issue, you were talking about "local inventory xml file". For that, this is indeed an administrator problem if you create a folder to store local inventory under the glpi-agent installation folder. I don't think glpi-agent should remove the folder setup as LOCAL.
But you can set it to be under var, etc or logs and it will be removed.
