### ISSUE TITLE
Typo line 589 in perl script for linux

### ISSUE THREAD

**Issue by Orchal** [glpi-project/glpi-agent#542]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

Hi,

it seems a "$" is missing in front of self on line 589 so the installation leds to the following error:
`Can't locate object method "open_os_file" via package "self" (perhaps you forgot to load "self"?) at ./glpi-agent-1.6.1-linux-installer.pl line 589`

There's no error if I add the "$" character.

Thanks

### To reproduce

Just run the installer without specify the distro.

### Expected behavior

Install should run with no errors

### Operating system

Linux

### GLPI Agent version

1.6.1

### GLPI version

10.0.10

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.3.3

**Comment by g-bougard** [comment]
Hello @Orchal 

thank you for your report. This issue is a duplicated of just closed #541, same issue, same answer:

This issue has been fixed few days ago in https://github.com/glpi-project/glpi-agent/commit/854ee13d869404f4ee318d06ed4a627ea9a0283e.

It implies the current configuration is finally not kept. So you'll have to reconfigure your agent.

You can use [latest nightly build](https://nightly.glpi-project.org/glpi-agent/) to avoid the problem.

**Comment by Orchal** [comment]
Hello,

sorry for the duplicate, I tried to find using open_os_file but it was a screenshot in #541 hehe.
Thanks for the fix!
