### ISSUE TITLE
Typo in glpi-agent-1.6.1-linux-installer.pl

### ISSUE THREAD

**Issue by iZlovreD** [glpi-project/glpi-agent#544]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

While instalation get error:
`Can't locate object method "open_os_file" via package "self" (perhaps you forgot to load "self"?) at glpi-agent-1.6.1-linux-installer.pl line 589.`

In pl file missing "$" before `self->` at 589 line:
`        my $fh = self->open_os_file($installed_config, '>')
            or die "Can't create $installed_config: $!\n";
`

### To reproduce

Instalation process with options

### Expected behavior

Install agent

### Operating system

Linux

### GLPI Agent version

1.6.1

### GLPI version

9.5.13

### GLPIInventory plugin or FusionInventory for GLPI plugin version

FusionInventory for GLPI v9.5+4.2

**Comment by g-bougard** [comment]
Hello @iZlovreD 

thank you for your report. But this issue is a duplicated of closed #541 & #542, same issue, same answer:

This issue has been fixed few days ago in https://github.com/glpi-project/glpi-agent/commit/854ee13d869404f4ee318d06ed4a627ea9a0283e.

It implies the current configuration is finally not kept. So you'll have to reconfigure your agent.

You still can use [latest nightly build](https://nightly.glpi-project.org/glpi-agent/) to avoid the problem.

**Comment by iZlovreD** [comment]
> This issue has been fixed few days ago in [854ee13](https://github.com/glpi-project/glpi-agent/commit/854ee13d869404f4ee318d06ed4a627ea9a0283e).

Yep, but not yet released.
