### ISSUE TITLE
Typo bug in installation script

### ISSUE THREAD

**Issue by laurentmele** [glpi-project/glpi-agent#555]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

When I try to install glpi agent on linux I have this error message : 

perl glpi-agent-1.6.1-linux-installer.pl --install -S -s 'https://myserver.glpi.fr/glpi/' --cron
Can't locate object method "open_os_file" via package "self" (perhaps you forgot to load "self"?) at glpi-agent-1.6.1-linux-installer.pl line 589.

Edit the file at line 589 we have : 

my $fh = self->open_os_file($installed_config, '>')

The $ before self is missing. Execution is ok when we add it.

### To reproduce

Download the perl package
try to execute it

### Expected behavior

Should install normally

### Operating system

Linux

### GLPI Agent version

1.6.1

### GLPI version

Not applicable

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Not applicable

**Comment by g-bougard** [comment]
Hello @laurentmele 

thank you for your report. This issue is a duplicated of closed #541, #542, and #544, same issue, same answer:

This issue has been fixed some days ago in https://github.com/glpi-project/glpi-agent/commit/854ee13d869404f4ee318d06ed4a627ea9a0283e.

It implies the current configuration is finally not kept. So you'll have to reconfigure your agent.

You can use [latest nightly build](https://nightly.glpi-project.org/glpi-agent/) to avoid this problem.
