### ISSUE TITLE
glpi-agent-task-deploy Intallation on Rocky Linux 9

### ISSUE THREAD

**Issue by nykroy** [glpi-project/glpi-agent#619]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

On glpi-agent-task-deploy of 1.7.1-1 version i have problemas because the perl module Archive-Extract is not present
![image](https://github.com/glpi-project/glpi-agent/assets/7745881/6e899439-7665-4daa-a2c7-926cb5a76343)

If itry to install perl-Archive-Extarctor its  have problem with MODULE_COMPAT_5 that it is deprecatted on Rocky linux 9 
![image](https://github.com/glpi-project/glpi-agent/assets/7745881/c625bfa8-0076-486b-b2f3-3ada3a73976a)

### To reproduce

 Install rpm file of glpi-agent-task-deploy

### Expected behavior

 install correctly and enable deploy module

### Operating system

Linux

### GLPI Agent version

1.7.1

### GLPI version

10.0.12

### GLPIInventory plugin or other plugin version

GLPI Inventory v1.3.5

**Comment by g-bougard** [comment]
Hi @nykroy 

first of all, it's wrong to use repository from different OS level version: here you seem to enable EPEL for EL8 where you are on a RockyLinux 9. You probably need to upgrade your EPEL repository integration.

Also on EL9 you should now use dnf in place of yum.

Anyway I took time to check where has passed that package. It seems it has been removed from parent distro and I really don't know why. This means you won't just be able to install the deploy task on this distro. I'm sorry for that but this problem is not really in the agent but in the distro itself. I still see the package is in the staging: https://git.rockylinux.org/staging/rpms/perl-Archive-Extract as it was included in EL8. It is now removed from EL9 without evident reason.

You should probably contact EPEL to ask them to include it. Sorry, I don't know how to do this.

**Comment by nykroy** [comment]
i try to enable EPEL for EL8 on RockyLinux 9 and not EL9 to try solve this problem. I saw that it removed from EL9 and open this issue to inform you for future release if the package will be dead :)

Thanks for the plugin!!

**Comment by g-bougard** [comment]
Yes, thank you for the advertisement.

Maybe we will have to implement an alternative if this package remains out of that distro flavour.

**Comment by g-bougard** [comment]
Hi @nykroy 

I tried to remove the Archive::Extract dependency.

Can I ask you to test next nightly build ?

It would be nice also if you can validate you're able to deploy on linux commonly used archive formats.
