### ISSUE TITLE
Deploy feature is not install by default

### ISSUE THREAD

**Issue by tomamplius** [glpi-project/glpi-agent#686]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

Old agent version install deployement feature by default by 1.9 don't install this module

### To reproduce

Install glpi agent 1.9 with package to deploy on this computer. 

![image](https://github.com/glpi-project/glpi-agent/assets/6951820/52d9ef26-3e14-4cb7-ad2f-362912c7037c)

### Expected behavior

![image](https://github.com/glpi-project/glpi-agent/assets/6951820/71ce6238-0999-42cf-8cb2-6c3b6d9f0c09)

### Operating system

Windows

### GLPI Agent version

1.9

### GLPI version

10.0.15

### GLPIInventory plugin or other plugin version

GLPI Inventory v1.3.5

**Comment by g-bougard** [comment]
Hello @tomamplius 

as reported in [1.8 announcement](https://glpi-project.org/glpi-agent-release-1-8/), the feature was removed by default. Indeed it should only be installed if really used and correctly configured on server side. Otherwise if wrongly configured, a malicious user still having compromised the network or even the server hosting glpi could use it to install malicious payload on computers without leaving a chance to detect the problem to admins.

So I must admit I forgot to update the online documentation.

I will fix it asap.
