### ISSUE TITLE
ERROR: 500 Internal Server Error, Out of range value for column 'manufacturers_id' at row 1

### ISSUE THREAD

**Issue by tdelaux** [glpi-project/glpi-agent#704]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

Hello,
GLPI inventory not working with error "ERROR: 500 Internal Server Error, Out of range value for column 'manufacturers_id' at row 1"
Invetory file : [inventory.json](https://github.com/user-attachments/files/16125903/inventory.json)

 

### To reproduce

Import join file

### Expected behavior

import file correctly

### Operating system

Windows

### GLPI Agent version

1.9

### GLPI version

10.0.14

### GLPIInventory plugin or other plugin version

GLPI Inventory v1.x.x (See additional context below)

### Additional context

GLPI Inventory 1.9

**Comment by g-bougard** [comment]
Hi @tdelaux 

when providing json and after you edited it, you should still test you obtain the same error when you import it manually. Actually, your json is even no more valid as you leaved a comma in the "local_users" list. Then you changed ips on a network interface replacing them with invalid ips.

After fixing that wrong edition, I can import without any problem you inventory in a glpi 10.0.12 or 10.0.15 test instance.

So I can still tell you the problem is not on agent side, but on server side.

You should check glpi issues related to manufacturers_id: https://github.com/glpi-project/glpi/issues?q=is%3Aissue+manufacturers_id+is%3Aclosed
I hope one of these closed issue is related to your problem.
