### ISSUE TITLE
GLPI NetInventory - only first IP is inventoried

### ISSUE THREAD

**Issue by eduardomozart** [glpi-project/glpi-agent#705]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

When a device contains multiple "management" IP addresses, it seems that only the first IP (172.31.98.1) is checked when a NetInventory task is run:

<img width="976" alt="image" src="https://github.com/glpi-project/glpi-agent/assets/2974895/fa05574c-11dc-4b67-81ca-5570d04a8269">

Print of Network devices > [Device] > Network ports.

GLPI Agent Debug (Level 1) output:

```
[Mon Jul  8 16:03:39 2024][debug] new thread 12 to handle task NetInventory
[Mon Jul  8 16:03:39 2024][info] running task NetInventory
[Mon Jul  8 16:03:39 2024][debug] Current netinventory run expiration timeout: 1.0 hour
[Mon Jul  8 16:03:39 2024][debug] using 4 netinventory workers
[Mon Jul  8 16:03:40 2024][debug] #1, full snmp scan of 192.168.0.1 with credentials 2
[Mon Jul  8 16:03:40 2024][debug] #2, full snmp scan of 172.31.98.1 with credentials 2
[Mon Jul  8 16:03:41 2024][debug] #3, full snmp scan of 172.31.98.1 with credentials 2
[Mon Jul  8 16:03:41 2024][debug] #4, full snmp scan of 172.31.98.1 with credentials 2
[Mon Jul  8 16:03:55 2024][error] #1, SNMP communication error: no response from host 192.168.0.1
[Mon Jul  8 16:03:56 2024][error] #2, SNMP communication error: no response from host 172.31.98.1
[Mon Jul  8 16:03:56 2024][error] #3, SNMP communication error: no response from host 172.31.98.1
[Mon Jul  8 16:03:56 2024][error] #4, SNMP communication error: no response from host 172.31.98.1
```

Downloads:

GLPI Inventory file: [networkequipment_0_4.xml.txt](https://github.com/user-attachments/files/16134698/networkequipment_0_4.xml.txt)

### To reproduce

1. Create a new NetInventory task after a NetDiscovery task.
2. See error on GLPI Agent debug log.

### Expected behavior

If the contact with the device fails through the first IP, try the next one until the contact succeeds.

### Operating system

Windows

### GLPI Agent version

1.9

### GLPI version

10.0.16

### GLPIInventory plugin or other plugin version

GLPI Inventory v1.3.5

**Comment by g-bougard** [comment]
Hi @eduardomozart 

I really appreciate your effort to find a solution to this problem, but the problem is not on agent side, but on server side. And to be more accurate, this is a known problem with [glpi-inventory-plugin](https://github.com/glpi-project/glpi-inventory-plugin). The problem is the plugin, when handling the netdiscovery task results, sorts the ips and when it will prepare the netinventory task, it will keep the first management ip even if it is not in the ip range defined... This won't be a problem for most devices as most of the time, there's only one ip and if the ip is wrong it still sometime works. In your case, as you have a vlan ip as first in the list, it doesn't work.

Your solution in #706 works for you, but it is wrong for us: we don't actually want to remove a found ip from this list.

Here is a possible work-around for you: change the addressing of your aruba device to have the management ip in a 10.0.0.0/8 iprange. This way it should be sorted before the valn one in the plugin and should be used during netinventory task.

Anyway, you should open or reopen an issue on the plugin project linking this glpi-agent issue.

So I'm sorry I must close your issue as our solution is not agent side.
