### ISSUE TITLE
When Snmp inventory device has two management ip only try the first

### ISSUE THREAD

**Issue by jjmg84** [glpi-project/glpi-agent#802]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

Hi, when i have a network device discovered and it has two or more management ip addresses, only first ip address is tryed to connect for a snmp scan. if this ip has not connection from glpi server dont try to connect to second management ip

### To reproduce

Create or discover a network device with two management ip address, only second has connection to SNMP Scan Agent and then try to make inventary

### Expected behavior

If first ip is not accesible, then try to second, third... to make a connection and read snmp info.

### Operating system

Windows

### GLPI Agent version

v1.11

### GLPI version

10.0.16

### GLPIInventory plugin or other plugin version

GLPI Inventory v1.3.5

**Comment by g-bougard** [comment]
Hi @jjmg84 

as far I know, this problem is not a glpi-agent issue, but a glpi-inventory-plugin one. And I'm confident you would have still fixed this problem if you had upgrade it as a fix  was proposed and merged. Actual version is 1.4.0 and the related fix is this one: https://github.com/glpi-project/glpi-inventory-plugin/pull/524

The fix in the plugin should force to use the ip which is in the defined ip range. Please, don't tell me the 2 management ips are in the same ip range.

So upgrade your plugin.

**Comment by jjmg84** [comment]
Hi, i updated to 1.4.0 but it is still happening 

@g-bougard 


![Image](https://github.com/user-attachments/assets/a64ef391-eb3b-45eb-a763-3a5479f4ef21)

![Image](https://github.com/user-attachments/assets/cc4ff710-ea40-4a6e-8d01-f41568422e88)

i must do anything more to make it work? 

Thanks!

**Comment by g-bougard** [comment]
You should probably just open an issue on the glpi-inventory-plugin project as @stonebuzz (as he is the one who fixed the problem initially on the plugin) will be the best person to explain you what could be wrong in your case.
