### ISSUE TITLE
Deployment using P2P shouldn't scan network and broadcast addresses

### ISSUE THREAD

**Issue by larsen0815** [glpi-project/glpi-agent#804]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

When you deploy a package and use the "p2p" option, GLPI agent scans every host in every network, but also the network and the broadcast address, e.g.:
> 192.168.191.255:62354 (The selected IP address is not valid in this context.)
> 192.168.188.255:62354 (The selected IP address is not valid in this context.)
> 192.168.86.255:62354 (The selected IP address is not valid in this context.)
> 192.168.56.255:62354 (The selected IP address is not valid in this context.)
> 192.168.98.255:62354 (The selected IP address is not valid in this context.)
> 192.168.0.255:62354 (The selected IP address is not valid in this context.)

### To reproduce

1.  Create a package deployment using the "p2p" option
2. Run the task on a client
3. Watch the agent's log

### Expected behavior

For a network 192.168.0.0/24, the IPs 192.168.0.0 and 192.168.0.255 should not be scanned.

### Operating system

Windows

### GLPI Agent version

v1.10

### GLPI version

Other (See additional context below)

### GLPIInventory plugin or other plugin version

Other (See additional context below)

### Additional context

GLPI 10.0.17 (missing from the dropdown, atm)
GLPIInventory 1.4.0 (missing from the dropdown, atm)

**Comment by g-bougard** [comment]
Hi @larsen0815 

thank you for your report.

This is the first time I see this error. Maybe it is operating system related. Indeed, I didn't find a way to reproduce that error.

Anyway, it makes sens to fix it.

Can you try to apply the following patch on one peer and check the problem is fixed there ?
```patch
diff --git a/lib/GLPI/Agent/Task/Deploy/P2P.pm b/lib/GLPI/Agent/Task/Deploy/P2P.pm
index 84084caf4..3189ddead 100644
--- a/lib/GLPI/Agent/Task/Deploy/P2P.pm
+++ b/lib/GLPI/Agent/Task/Deploy/P2P.pm
@@ -187,10 +187,16 @@ sub _getPotentialPeers {
         push @end,   $ip_bytes[$idx] | (255 - $mask_bytes[$idx]);
     }
 
+    # ipEnd must not be the broadcast ip
+    $end[3]--;
+
     my $ipStart = join('.', @start);
     my $ipEnd   = join('.', @end);
     return if $ipStart eq $ipEnd;
 
+    # ipStart is here the network address to avoid
+    my $ipNetwork = $ipStart;
+
     # Get ip interval before this interface ip
     my $ipIntervalBefore = Net::IP->new($ipStart.' - '.$address->{ip})
         or die Net::IP::Error();
@@ -230,6 +236,13 @@ sub _getPotentialPeers {
     $ipStart = $ipIntervalBefore->ip();
     $beforeCount = $ipIntervalBefore->size() - 1;
 
+    # Still skip first address if it's the network address
+    if ($ipStart eq $ipNetwork) {
+        ++$ipIntervalBefore;
+        $beforeCount--;
+        $ipStart = $ipIntervalBefore->ip() if defined($ipIntervalBefore);
+    }
+
     # Now add ips before
     my @peers;
     while (defined($ipIntervalBefore) && $beforeCount-->0) {
```

**Comment by g-bougard** [comment]
I just pushed an updated patch with updated unittests.

You'll be able to validate with next nightly build.

**Comment by larsen0815** [comment]
I downloaded the ZIP for "GLPI-Agent-1.12-git03222e35-x64", extracted it to my test directory, set "debug=2" and "tasks = deploy" in agent.cfg and ran it this way:

```
c:\1temp\GLPI-Agent-1.12-git03222e35-x64>.\glpi-agent.bat --force --logger=stderr --server http://glpi.example.local/marketplace/glpiinventory/
.... 
[debug2] http://glpi.example.local/marketplace/glpiinventory/?action=getConfig&machineid=atl-burg-2024-11-14-10-32-11&task[Deploy]=3.3
[error] [http client] communication error: 400 Bad Request
[info] Deploy task not supported by server0
...
```

Is Deploy 3.3 too new for the server?

btw: https://nightly.glpi-project.org/glpi-agent/ only shows "Built on UTC" instead of the date it was built on.

**Comment by g-bougard** [comment]
Hi @larsen0815 

first, you got the wrong nightly as the latest was not build in time. It was blocked because of missing latest Apple agreement. It has just been fixed and I forced the MacOSX builds to restart so latest build is finally published.

The first from the list is always the latest. I understand you didn't figure out which one was the latest as only one had a build date and it was a week ago. Just for your information, a nightly build is published only if a code update has been pushed during the last 24 hours. Anyway, I'll try to fix the nightly build date missing problem.

No, the Deploy version is not too new. For your error, you should first make an inventory as running this way, the deviceid is changed in glpi. Depending on how your Deploy task includes assets, it may know of this agent, so you can have to update it after the first inventory.
And don't forget to use `--debug --debug` when testing this way from the commandline.

You can also directly install the MSI as it is really close to v1.11. And if you have any trouble or just want to revert, just install v1.11 MSI other it.

**Comment by larsen0815** [comment]
Thanks! Got it running after reassigning my computer in the task. So, removed "atl-burg" and then added "atl-burg". A little bit confusing why this is needed.

P2P is now **not** scanning network and broadcast addresses anymore.

Another question if I may. I already created a [thread](https://forum.glpi-project.org/viewtopic.php?pid=513942) for this:
Is there a way to tell the agent to only scan a specific network for P2P transfers?
(e.g. I am at home right now, connected via VPN to my company, and the chances of having a peer in my private network are next to zero :wink:)

**Comment by g-bougard** [comment]
Sorry, no, there's actually no way to specify where network can or cannot be scanned for agent.

Agent P2P support is pretty old and should probably be upgraded to a better solution in the future.
